services:
  db:
    image: postgres:15.1
    restart: 'always'
    ports:
      - '8081:5432'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - monitoring

  app:
    build: .
    container_name: library-api
    ports:
      - '8080:8080'
    labels:
      - "prometherus-job=library-api"
    networks:
      - monitoring
    depends_on:
      db:
       condition: service_healthy
  
  prometherus:
    image: prom/prometheus
    container_name: prometherus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
    - '9090:9090'
    depends_on:
      - app
    networks:
      - monitoring

  grafana:
   image: grafana/grafana:latest
   container_name: grafana
   ports:
    - '3000:3000'
   environment:
   - GF_SECURITY_ADMIN_PASSWORD=admin
   networks:
    - monitoring
  
networks:
  monitoring: