// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/Lucifer07/e-wallet/entity"
	mock "github.com/stretchr/testify/mock"
)

// BankTransactionRepository is an autogenerated mock type for the BankTransactionRepository type
type BankTransactionRepository struct {
	mock.Mock
}

// CreateBankAccount provides a mock function with given fields: ctx, accountNumber
func (_m *BankTransactionRepository) CreateBankAccount(ctx context.Context, accountNumber int) (*entity.BankAccount, error) {
	ret := _m.Called(ctx, accountNumber)

	var r0 *entity.BankAccount
	if rf, ok := ret.Get(0).(func(context.Context, int) *entity.BankAccount); ok {
		r0 = rf(ctx, accountNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.BankAccount)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, accountNumber)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
