// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/Lucifer07/e-wallet/entity"
	mock "github.com/stretchr/testify/mock"
)

// CCTransactionRepository is an autogenerated mock type for the CCTransactionRepository type
type CCTransactionRepository struct {
	mock.Mock
}

// CreateCCAccount provides a mock function with given fields: ctx, ccNumber
func (_m *CCTransactionRepository) CreateCCAccount(ctx context.Context, ccNumber int) (*entity.CreditCardAccount, error) {
	ret := _m.Called(ctx, ccNumber)

	var r0 *entity.CreditCardAccount
	if rf, ok := ret.Get(0).(func(context.Context, int) *entity.CreditCardAccount); ok {
		r0 = rf(ctx, ccNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.CreditCardAccount)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, ccNumber)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
