// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/Lucifer07/e-wallet/dto"
	mock "github.com/stretchr/testify/mock"
)

// PasswordTokenService is an autogenerated mock type for the PasswordTokenService type
type PasswordTokenService struct {
	mock.Mock
}

// CreateResetPassword provides a mock function with given fields: ctx, email
func (_m *PasswordTokenService) CreateResetPassword(ctx context.Context, email dto.GettokenRequest) (*dto.GetTokenResponse, error) {
	ret := _m.Called(ctx, email)

	var r0 *dto.GetTokenResponse
	if rf, ok := ret.Get(0).(func(context.Context, dto.GettokenRequest) *dto.GetTokenResponse); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.GetTokenResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, dto.GettokenRequest) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ResetPassword provides a mock function with given fields: ctx, tokenPassword
func (_m *PasswordTokenService) ResetPassword(ctx context.Context, tokenPassword dto.TokenPassword) error {
	ret := _m.Called(ctx, tokenPassword)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.TokenPassword) error); ok {
		r0 = rf(ctx, tokenPassword)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
