// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/Lucifer07/e-wallet/entity"
	mock "github.com/stretchr/testify/mock"
)

// PayLaterTransactionRepository is an autogenerated mock type for the PayLaterTransactionRepository type
type PayLaterTransactionRepository struct {
	mock.Mock
}

// CreatePayLaterTransaction provides a mock function with given fields: ctx, userId
func (_m *PayLaterTransactionRepository) CreatePayLaterTransaction(ctx context.Context, userId int) (*entity.PaylaterAccount, error) {
	ret := _m.Called(ctx, userId)

	var r0 *entity.PaylaterAccount
	if rf, ok := ret.Get(0).(func(context.Context, int) *entity.PaylaterAccount); ok {
		r0 = rf(ctx, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.PaylaterAccount)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
